
title: 2019 My LA2050 Grants Challenge
description: >-
  The My LA2050 Grants Challenge is an open call for ideas to make LA the best place to
  learn, create, play, connect, and live.
image: https://challenge.la2050.org/assets/images/city-illustration/square.png

mailing_list_url: https://la2050.us6.list-manage.com/subscribe/post?u=81b6d7b4efb839b992bf7ae72&amp;id=b16f498212
submission_url: https://challengela2050.smapply.io

# Our form:
vote_url: /vote/form/

year: 2019
show_early_entries: true

# New challenge announced: 
# January 8
# phase: 1

# Entries being accepted: 
# February 28
# phase: 2

# Entry period ended: 
# March 29
phase: 3

# Entries shown on the website: 
# April 15
# phase: 4

# Votes being accepted: 
# April 22
# phase: 5

# Voting period ended: 
# April 29
# phase: 6

# Finalists announced: 
# ?
# phase: 7

# Winners announced: 
# June 4
# phase: 8


finalists:

  # Learn
  # 1)
  # 2)
  # 3)
  # 4)
  # 5)
  # 6)
  # 7)
  # 8)
  # 9)
  # 10)

  # Create
  # 1)
  # 2)
  # 3)
  # 4)
  # 5)
  # 6)
  # 7)
  # 8)
  # 9)
  # 10)

  # Play
  # 1)
  # 2)
  # 3)
  # 4)
  # 5)
  # 6)
  # 7)
  # 8)
  # 9)
  # 10)

  # Connect
  # 1)
  # 2)
  # 3)
  # 4)
  # 5)
  # 6)
  # 7)
  # 8)
  # 9)
  # 10)

  # Live
  # 1)
  # 2)
  # 3)
  # 4)
  # 5)
  # 6)
  # 7)
  # 8)
  # 9)
  # 10)


winners:
  # 1)
  # 2)
  # 3)
  # 4)
  # 5)


auth0_js_url: https://cdn.auth0.com/js/auth0/9.5.1/auth0.min.js
# auth0_domain: activation-la2050.auth0.com
auth0_domain: auth0-activation.la2050.org
auth0_client_id: INfJpr4dnNk2EN143utsZYz4Zeq9c7cd

voting_enable_auth0: true

voting_enable_phone: true
voting_enable_email: true
voting_enable_facebook: true

voting_maintance_mode: false
voting_test_mode: false

voting_strict_mode: true

# For cache busting
version: 2.1.9


permalink: pretty

exclude:
  - CNAME
  - README
  - Gemfile
  - Gemfile.lock
  - _node
  - sitemap.txt
  - test-finalists.txt
  - assets/images/2019/learn/original
  - assets/images/2019/create/original
  - assets/images/2019/play/original
  - assets/images/2019/connect/original
  - assets/images/2019/live/original
  - assets/images/goals/original
  - assets/images/home/original
  - assets/images/vote/original

defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      path: ""
      type: "2019"
    values:
      layout: project

collections:
  '2019':
    output: true
    permalink: /2019/:path/
